<?xml version="1.0" encoding="utf-8"?><testsuites name="pytest tests"><testsuite name="pytest" errors="1" failures="0" skipped="0" tests="1" time="0.480" timestamp="2025-09-24T23:38:26.514461+03:30" hostname="DESKTOP-B9H9OEV"><testcase classname="" name="tests.test_presign_unit" time="0.000"><error message="collection failure">ImportError while importing test module 'C:\Users\moham\OneDrive\Desktop\GitHub\infra\tests\test_presign_unit.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
..\..\..\..\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tests\test_presign_unit.py:3: in &lt;module&gt;
    from generate_presigned_put import generate_presigned_put
E   ModuleNotFoundError: No module named 'generate_presigned_put'</error></testcase></testsuite></testsuites>